// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/raftpb/command.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Op int32

const (
	Op_OP_UNSPECIFIED Op = 0
	Op_OP_PUT         Op = 1
	Op_OP_DELETE      Op = 2
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "OP_PUT",
		2: "OP_DELETE",
	}
	Op_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"OP_PUT":         1,
		"OP_DELETE":      2,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_raftpb_command_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_proto_raftpb_command_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_proto_raftpb_command_proto_rawDescGZIP(), []int{0}
}

// Command is the envelope for any write applied through Raft.
// Reads bypass Raft entirely.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // ULID, generated by API server (Phase 0.5b)
	Op            Op                     `protobuf:"varint,2,opt,name=op,proto3,enum=raftpb.Op" json:"op,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"` // empty for OpDelete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_raftpb_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raftpb_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_raftpb_command_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Command) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_OP_UNSPECIFIED
}

func (x *Command) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Command) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_proto_raftpb_command_proto protoreflect.FileDescriptor

const file_proto_raftpb_command_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/raftpb/command.proto\x12\x06raftpb\"l\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\x02op\x18\x02 \x01(\x0e2\n" +
	".raftpb.OpR\x02op\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value*3\n" +
	"\x02Op\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06OP_PUT\x10\x01\x12\r\n" +
	"\tOP_DELETE\x10\x02B\x1dZ\x1bdistributed-kv/proto/raftpbb\x06proto3"

var (
	file_proto_raftpb_command_proto_rawDescOnce sync.Once
	file_proto_raftpb_command_proto_rawDescData []byte
)

func file_proto_raftpb_command_proto_rawDescGZIP() []byte {
	file_proto_raftpb_command_proto_rawDescOnce.Do(func() {
		file_proto_raftpb_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_raftpb_command_proto_rawDesc), len(file_proto_raftpb_command_proto_rawDesc)))
	})
	return file_proto_raftpb_command_proto_rawDescData
}

var file_proto_raftpb_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_raftpb_command_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_raftpb_command_proto_goTypes = []any{
	(Op)(0),         // 0: raftpb.Op
	(*Command)(nil), // 1: raftpb.Command
}
var file_proto_raftpb_command_proto_depIdxs = []int32{
	0, // 0: raftpb.Command.op:type_name -> raftpb.Op
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_raftpb_command_proto_init() }
func file_proto_raftpb_command_proto_init() {
	if File_proto_raftpb_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_raftpb_command_proto_rawDesc), len(file_proto_raftpb_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_raftpb_command_proto_goTypes,
		DependencyIndexes: file_proto_raftpb_command_proto_depIdxs,
		EnumInfos:         file_proto_raftpb_command_proto_enumTypes,
		MessageInfos:      file_proto_raftpb_command_proto_msgTypes,
	}.Build()
	File_proto_raftpb_command_proto = out.File
	file_proto_raftpb_command_proto_goTypes = nil
	file_proto_raftpb_command_proto_depIdxs = nil
}
